version: '3'

services:
  server:
    build:
      context: ./
      target: production-build-stage
    ports:
      - "${APP_PORT:-3070}:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
