version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 3071:3071
    volumes:
      - .:/home/node/app
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"

  