version: "3.7"

services:
  workspace:
    build:
      context: ./.docker/bin/workspace
      args:
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
    container_name: '01dev-workspace'
    ports:
      - ${WORKSPACE_HTTP_PORT}:3052
      - ${WORKSPACE_SSH}:22
    volumes:
      - ${DOCUMENT_ROOT}:/var/www
    networks:
      - backend

networks:
  backend:
    driver: bridge
