version: "3.7"

services:
  workspace:
    build:
      context: ./.docker/bin/workspace
      args:
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
    container_name: '01dev-workspace'
    ports:
      - ${WORKSPACE_HTTP_PORT}:3052
      - ${WORKSPACE_SSH}:22
      - "${APP_PORT:-3031}:3031"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - backend

networks:
  backend:
    driver: bridge
